<?php
/**
 * English Language File - Common Translations
 * @package SLPA\Languages
 */

return [
    // Common
    'app_name' => 'SLPA Inventory System',
    'welcome' => 'Welcome',
    'dashboard' => 'Dashboard',
    'logout' => 'Logout',
    'login' => 'Login',
    'username' => 'Username',
    'password' => 'Password',
    'remember_me' => 'Remember Me',
    'forgot_password' => 'Forgot Password?',
    
    // Actions
    'save' => 'Save',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'view' => 'View',
    'add' => 'Add',
    'search' => 'Search',
    'filter' => 'Filter',
    'export' => 'Export',
    'import' => 'Import',
    'print' => 'Print',
    'refresh' => 'Refresh',
    'submit' => 'Submit',
    'reset' => 'Reset',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'close' => 'Close',
    
    // Navigation
    'home' => 'Home',
    'users' => 'Users',
    'papers' => 'Papers',
    'ribbons' => 'Ribbons',
    'toner' => 'Toner',
    'master' => 'Master',
    'receiving' => 'Receiving',
    'issuing' => 'Issuing',
    'return' => 'Return',
    'returns' => 'Returns',
    'reports' => 'Reports',
    'settings' => 'Settings',
    
    // Messages
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Information',
    'confirm_delete' => 'Are you sure you want to delete this item?',
    'no_data' => 'No data available',
    'loading' => 'Loading...',
    'processing' => 'Processing...',
    'saved_successfully' => 'Saved successfully',
    'deleted_successfully' => 'Deleted successfully',
    'operation_failed' => 'Operation failed',
    
    // Validation
    'required_field' => 'This field is required',
    'invalid_email' => 'Invalid email address',
    'invalid_phone' => 'Invalid phone number',
    'password_too_short' => 'Password must be at least {min} characters',
    'passwords_dont_match' => 'Passwords do not match',
    'invalid_date' => 'Invalid date format',
    
    // Pagination
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'entries' => 'entries',
    'entries_plural' => 'entries',
    'page' => 'Page',
    'per_page' => 'Per Page',
    
    // Date/Time
    'date' => 'Date',
    'time' => 'Time',
    'today' => 'Today',
    'yesterday' => 'Yesterday',
    'tomorrow' => 'Tomorrow',
    'this_week' => 'This Week',
    'last_week' => 'Last Week',
    'this_month' => 'This Month',
    'last_month' => 'Last Month',
    'decimal_point' => '.',
    'thousands_separator' => ',',
    'currency_LKR' => 'Rs.',
    'currency_USD' => '$',
    'currency_EUR' => '€',
    'currency_position' => 'before',
    
    // Inventory
    'quantity' => 'Quantity',
    'unit_price' => 'Unit Price',
    'total_price' => 'Total Price',
    'stock_level' => 'Stock Level',
    'reorder_level' => 'Reorder Level',
    'supplier' => 'Supplier',
    'category' => 'Category',
    'description' => 'Description',
    'item_code' => 'Item Code',
    'item_name' => 'Item Name',
    
    // User Management
    'full_name' => 'Full Name',
    'email' => 'Email Address',
    'phone' => 'Phone Number',
    'role' => 'Role',
    'status' => 'Status',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    
    // Reports
    'report_title' => 'Report Title',
    'report_date' => 'Report Date',
    'generated_by' => 'Generated By',
    'total' => 'Total',
    'subtotal' => 'Subtotal',
    'grand_total' => 'Grand Total',
    
    // Workflow
    'pending_approval' => 'Pending Approval',
    'approved' => 'Approved',
    'rejected' => 'Rejected',
    'approve' => 'Approve',
    'reject' => 'Reject',
    'comments' => 'Comments',
    
    // Search
    'search_results' => 'Search Results',
    'no_results_found' => 'No results found',
    'search_for' => 'Search for',
    'advanced_search' => 'Advanced Search',
    'saved_searches' => 'Saved Searches',
];
